version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT_ENABLE_FASTEMBED=true
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION_NAME=documents
      - VECTOR_SIZE=384
    depends_on:
      - qdrant
    volumes:
      - ./uploads:/app/uploads
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always 