// List of available knowledge domains for document processing
export const availableDomains = [
  'nội kinh',
  'khí công',
  'kinh dịch',
  'dịch cân kinh',
  'thái cực khí công',
  'bát đoạn cẩm',
  'ngũ cầm hí',
  'đông y',
  'y học cổ truyền',
  'y tông tâm lĩnh',
  'hải thượng lãn ông',
  'lê hữu trác',
  'y quán',
  'y quán đường',
  'âm dương ngũ hành',
  'dịch lý',
  'lão kinh',
  'lão tử',
  'phong thủy',
  'đạo phật',
  'thích nhất hạnh',
  'viên minh',
  'phí tường trúc'
];